# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      

      - name: test
        run: |
          pytest
          
      - name: integration
        run: echo je suis entraind d'essayer d'integrer mon code dans la branche main

      - name: lint
        run: |
          pip install pylint
          pylint .
